name: npm test

on: [push]

jobs:

  test:

    runs-on: ubuntu-latest

    strategy:

      matrix:

        node_version: [12.x]

    steps:

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}

        uses: actions/setup-node@v1

        with:

          node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: npm run build --if-present

  push-to-registry:

    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps: 
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker push je11alvaradom/testgit:primer
        with: 
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker push je11alvaradom/testgit:nsegunda
        with: 
          images: je11alvaradom/prueba

      - name: Build and push Docker image
        uses: docker push je11alvaradom/testgit:tercera
        with: 
          context: .
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
